### PR TITLE
Revise Tranaslator to add NText for insert/update SQL Server utf-8 character

### PR DESCRIPTION
**Pull request by MartinHsu**
- bug fix / new feature?   
- BC break? yes/no

### CODE REVIEW

**Comment by dg** [comment]
IIs not the solution to switch the database to utf-8?

**Comment by Dacesilian** [comment]
> Is not the solution to switch whole database to utf-8?

This should also be used for sqlsrv - there is the same problem with UTF-8.

**Comment by dg** [comment]
Great, thank you

**Comment by dg** [comment]
Related to #332

**Comment by MartinHsu** [comment]
> Related to #332

Thank you!

**Pull request closed without merging**
