### PR TITLE
Namespaces

### PR DESCRIPTION
**Pull request by dg**
It should work with code that uses non-namespaced dibi too.

We have two alternatives for class `dibi`:

1) class `dibi` without namespace
2) class `Dibi\Dibi` in namespace

### CODE REVIEW

**Comment by milo** [comment]
With `Dibi\Types` is the `Dibi` class only a standalone registry. And with a old names loader, `\dibi` vs. `Dibi\Dibi` does not matter for BC. Only I can think about is the IDE error reporing on non-existent `\dibi` class for the static-dibi users.

**Comment by dg** [comment]
I think that purpose of class `dibi` is its simplicity, so name `dibi` suits better than `Dibi\Dibi`.

But this could be problem:

```
use dibi;
dibi::query(...); // this is OK
$conn = new Dibi\Connection(...); // this will autoload dibi/Connection which will fail
```

Solution is to prefer Dibi before dibi.

**Comment by dg** [comment]
Btw, is better `Types::DATETIME` or `Type::DATETIME`?

**Comment by castamir** [comment]
`Types::DATETIME` :+1:

**Comment by JanTvrdik** [comment]
Are you targeting 3.0 or 2.4?

**Comment by dg** [comment]
I am targeting 2.4, it should be 100% same and compatible except for 4293ef2ac31773660a7d7d82b42d4db17eeab8c3.

I don't know how to be 100% compatible with non-namespaced dibi without another autoloader.

**Comment by milo** [comment]
> But this would be a problem

Maybe you fixed that, but I cannot get any error with following, so I don't understand the problem.
```php
namespace Foo;
use dibi;

error_reporting(E_ALL | E_STRICT);

require __DIR__ . '/../dibi/vendor/autoload.php';

$conf = ['driver' => 'postgre', 'user' => 'test', 'password' => 'test'];

var_dump(get_class(dibi::connect($conf)));
var_dump(get_class(new Dibi\Connection($conf)));
```

**Comment by milo** [comment]
>  Btw, is better Types::DATETIME or Type::DATETIME?

Hard to say. Would be easy for an object `new Dibi\Type`, but as a static class, I don't know. The
```php
$db->query(...)->setType(Type::BOOL)
```
fits me better.

**Comment by dg** [comment]
Yes, now it is fixed https://github.com/dg/dibi/blob/b5815137e85a60acfb919965475ecfdc401dd561/src/dibi.php#L132-L147.

Preloading is important for catching DibiException too, etc.

**Comment by JanTvrdik** [comment]
OK, why? What's the benefit of using namespaces in 2.x? Here's how I see it:

* You can never remove support for non-namespace class names (e.g. `DibiConnection`) in 2.x because it would break every library depending on dibi `~2.0`
* Supporting both class names with and without namespace is an ugly hybrid state. The purpose of the hybrid state is reduce the bloodshed caused by moving to namespace-only supported by default + optionally enabling compatibility with old names (but this can not be done in 2.x)
* If we release this as 2.4, new and actively maintained libraries will modify requirement `~2.0` to `~2.4` and start using new class names. Old libraries/projects will continue to work.
* Then we release 3.0 with namespace-only support by default + optionally enabling compatibility with old names. New and actively maintained libraries will modify requirement `~2.4` to `~2.4 OR ~3.0`. If projects use only actively maintained libraries, it will use 3.0, otherwise it will fall back to 2.4.

However this assumes that 3.0 will have identical API with 2.4 (except for compatibility enabled/disable by default). Because I don't think that 3.0 will have identical API with 2.4, I don't understand how this hybrid state is going to help with the transition from 2.x to 3.x.

How much am I wrong?

**Comment by dg** [comment]
Pros: 

1) It is 100% compatible with 2.3 (except you write own driver)
2) You can use namespaces immediatelly
3) 3.0 code will be very close to 2.3, which will make cherry-picking much and much easier

Cons:

1) none

Point 3) is for me absolutely fundamentally important.

**Comment by dg** [comment]
ad Types vs Type: according to .NET: „Use a singular name for most Enum types, but use a plural name for Enum types that are bit fields.“ 

Otherwise the signature of the method would have been i.e. `setDay(Days day)`. 

PHP has not native enums, but `Type::TEXT` make more sense in the context of where is used than `Types::TEXT`.

**Comment by milo** [comment]
Another point of view... simple constant would be written as singular `TYPE_TEXT` too.

**Comment by dg** [comment]
Ok, so I will use `Type` and `\dibi`. 

Now I'll release beta a we can test it.

**Pull request merged**
