### PR TITLE
SqLite: Fix fatal error when resource closed prior to result destructing

### PR DESCRIPTION
**Pull request by dakujem**
Bug fix; bc break: NO

I'm running into an issue in a certain setup with SqLite driver:
image

See, the resource has already been closed before the destruction of the result object.

Adding `is_resource` check is an efficient way to prevent it, possibly even the suppression operator `@` on line 40 might become redundant after this change.

I'm guessing this is similar to #409.

### CODE REVIEW

**Comment by dakujem** [comment]
I forgot to add that this only happens with PHP 8 and above.

**Comment by dakujem** [comment]
@dg bump.

**Comment by dg** [comment]
`is_resource($this->getResultResource())` this will always return false, that's probably not the right fix…

**Comment by dakujem** [comment]
I fail to understand the reason for rejecting this PR. If it did not happen I would not have been fixing it.  
Why do you think `is_resource($this->getResultResource())` will always evaluate to `false`?

**Comment by dakujem** [comment]
How is this different to #431?

**Comment by dg** [comment]
Because getResultResource() returns object.

**Comment by dakujem** [comment]
... and in 8e7df8374b42ca3810847dec587f7032ebed0732 you completely removed the auto-free feature, which renders this PR as well as #431 irrelevant anyway.

**Pull request closed without merging**
