### PR TITLE
DibiPdoDriver::escape() added support for dblib

### PR DESCRIPTION
**Pull request by baasha**
Fixed escaping for linux version of mssql driver - dblib.

### CODE REVIEW

**Comment by bckp** [comment]
Haha, I have this fix to prepared for commit :+1:

**Comment by dg** [comment]
Commit message should be `DibiPdoDriver::escape() added support for dblib` or something similar

**Comment by baasha** [comment]
@dg : OK, agree, title changed. *Order muß sein* :-)  :+1:

**Comment by dg** [comment]
Great, but title is not too important, change commit message.

**Comment by baasha** [comment]
Spent a nice hour studying how to change commit message in git ... feel powerful now  ;)

**Comment by dg** [comment]
Thanks!

**Pull request merged**
