### PR TITLE
Fluent TypeError fix

### PR DESCRIPTION
**Pull request by milo**
- bug fix? yes
- new feature? no
- BC break? (probably) no

Not sure the Sqlite3Driver fix is OK, but I think yes. Fixed only to pass tests :o)

### CODE REVIEW

**Comment by milo** [comment]
Hmm, more drivers are failing, they returns `Result` instead of affected rows count.

What would you prefer to do with it? Fix drivers, switch/case in test by driver, or other testing way?

**Comment by dg** [comment]
Do you mean to remove the functionality that query() returns the number of affected rows?

**Comment by dg** [comment]
merged

**Comment by milo** [comment]
Thank you!

**Pull request closed without merging**
