### PR TITLE
AppVeyor - testing on SQL Server [WIP]

### PR DESCRIPTION
**Pull request by dg**
- https://ci.appveyor.com/project/dg/dibi

### CODE REVIEW

**Comment by mhujer** [comment]
I've tried to make dibi run there but I did not succed. See https://github.com/dg/dibi/compare/master...mhujer:appveyor `tests/databases.appveyor.ini` may be useful for this PR

**Comment by dg** [comment]
CI AppVeyor works, but some tests fails on SQL Server.

**Comment by DiGi** [comment]
Few notes about MSSQL:

1. You should always use schemaName.objectName sytanx, everywhere. In CREATE scripts, in all DML. Table dbo.customers can be very different from sales.customers. MSSQL can cache plans and reuse them later
2. MSSQL doesn't support JOINS with USING syntax
3. Preffered TOP syntax is now TOP (n), not TOP n
4. You should always use ORDER BY if you use TOP. MSSQL does not guarantee any implicit ordering. For different ID you can get different plan using different index
5. You should alias computed columns, even in subselects

Related failures:

1. Connection.fetch.phpt(78), assert line 93, because note 2.
2. Just guess without SQL: Isn't generated SQL someting like SELECT COUNT(*) FROM (SELECT COUNT(*) FROM products ORDER BY product_id)? If so then there should be SELECT TOP (1) in inner SELECT
3. Error Fluent.select.phpt(100), generated SQL is probably "OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY" or "SELECT TOP 1". Test fails because it is not "odbc" and definitely is not "LIMIT 1"
4. Result.meta.phpt(19) will not work because note 2.
5. meta.phpt(20) same issue with test, not running "odbc" and you didn't get LIMIT 2

I don't have working PHP environment right now, but I hope that this can point you at some issues. Special 'odbc' code can be sometimes used for MSSQL too, but maybe it is better to write correct test.

**Comment by castamir** [comment]
ping @dg 

Is there any progress? I am trying to migrate my application to ms sql and so far I found out that fetch issue (using `OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY`) is still there.

**Comment by dg** [comment]
I will be glad if you send a pull request. I do not use MS SQL.

**Comment by castamir** [comment]
Ok, I'll try to fix this driver by myself

**Comment by dg** [comment]
:100:

**Pull request closed without merging**
