### PR TITLE
Support updating multiple tables at once

### PR DESCRIPTION
**Pull request by dakorpar**
-  new feature for dibi4, but this worked in dibi3
- BC break? no

This support giving multiple tables to update command on dibi
#314

### CODE REVIEW

**Comment by dg** [comment]
What about remove `string` from `update(string $table, ...)` ?

**Comment by dakorpar** [comment]
@dg that's probably better, just thought you want it that way :)

**Comment by dakorpar** [comment]
@dg can U maybe check why appveryor is failing? I believe it has nothing to do with this...
Any ETA on this PR and releasing new version?

**Comment by dg** [comment]
I plan to release a new version soon.

**Pull request merged**
