### PR TITLE
DibiMsSql2012Reflector for MSSQL2012 driver

### PR DESCRIPTION
**Pull request by kuty**
Copy of DibiMsSql2005 with some changes changes for MS SQL 2012

### CODE REVIEW

**Comment by dg** [comment]
How do they differ?

**Comment by dg** [comment]
ping @kuty

**Comment by kuty** [comment]
Finally from MSSQL 2012 there is limit and offset implemented and this is missing in 2005 server and of course driver.

**Comment by dg** [comment]
So why two drivers, you can improve current driver.

**Comment by kuty** [comment]
Because driver is called mssql2005 and there is now such possibility in 2005 version of MSSQL. You think it will be better to check everytime version of SQL server or have there such feature even there is no support?

**Comment by dg** [comment]
Probably better solution is to rename original driver, i.e. remove year from name, and support for limit and offset to the new driver.

**Comment by dg** [comment]
MsSql2005 driver renamed to Sqlsrv https://github.com/dg/dibi/commit/11027e25733ffeabf8dd057de0bca9ec247c3d2e

**Comment by kuty** [comment]
Perfect, thx

**Pull request closed without merging**
