### PR TITLE
HasmMap: fixed empty property name access

### PR DESCRIPTION
**Pull request by milo**
- bug fix? yes
- new feature? no
- BC break? no

See commit message.

### CODE REVIEW

**Comment by milo** [comment]
CS is failing due to `??` requirement https://travis-ci.org/dg/dibi/jobs/260983806#L554

**Comment by dg** [comment]
Is it PHP bug?

**Comment by milo** [comment]
I don't know. In doc is written, that "?? mutes warnings" like isset. That is not so exact statement. Maybe magic __isset() would help.

**Comment by dg** [comment]
Not a bug https://bugs.php.net/bug.php?id=72408

**Pull request merged**
