### PR TITLE
MySqliDriver::getResource() fixed usage of resource being closed prior to the call in PHP 8

### LINKED ISSUE #409: `MySqliDriver::getResource` throws in PHP 8 instead of returning `null` whe the resource has been closed prior to the call
Version: 4.2.5
PHP: 8.0, 8.1 (does not happen on PHP 7)

### Bug Description
`MySqliDriver::getResource()` **throws** an error in PHP 8 and is thus not suppressed by the `@` operator.

```
Fatal error: Uncaught Error: mysqli object is already closed
```

The problem is when this happens during shutdown with `EALL | E_STRICT` setting, when the connection service is being destructed.
I'm sharing the resource and it happens to be closed before the driver is destructed.

### Steps To Reproduce
```php
$driver = new MySqliDriver( ... );
$driver->getResource()->close();
$driver->getResource();
```

### Expected Behavior
I expect `null` to be returned instead of an internal error being thrown.

### Possible Solution

```php
    public function getResource(): ?\mysqli
    {
        if (!is_resource($this->connection)) {
            return null;
        }
        return @$this->connection->thread_id ? $this->connection : null;
    }
```
or
 ```php
    public function getResource(): ?\mysqli
    {
        try {
            return @$this->connection->thread_id ? $this->connection : null;
        } catch (\Error $e) {
            return null;
        }
    }
 ```

Let me know which alternative is better and I'll prepare a PR.

### PR DESCRIPTION
**Pull request by dakujem**
closes #409

### CODE REVIEW

**Comment by dakujem** [comment]
@dg I'm unable to configure the tests, help needed. I'm able to repliate the error via github actions in my fork, but appveyor uses different DB config provider.

**Comment by dakujem** [comment]
Also, I tried the `is_resource` condition, but the condition fails right after construction for some reason. I reimplemented it using a `try-catch` block.

**Comment by dg** [comment]
Thanks

**Comment by dakujem** [comment]
@dg The tests need to be updated. It was marked `WIP` for that reason. The code is ok, but I was unable to make the tests pass on appveyor. There's also the unused `mysqli-driver` config left dangling in the config files.

**Comment by dg** [comment]
I used a test like this: https://github.com/dg/dibi/commit/7d82ce2ff6b31055d57dea9026533c799f36c2c2#diff-1a3150d75da0d135bea2c37b25a578bf7aa75308db33a297abd067e27ffe558f

**Comment by dakujem** [comment]
If you're okay with the test, fine. Still, there's the dangling code that should be removed: https://github.com/dg/dibi/commit/8c2e425dfe3ea13687bb2f00aa595acf6098f3ab#diff-2e359a78bf001eae825dda38b8e9565c483c4a62089440534f2129aea7115538R26

Should I open a new PR?

**Comment by dg** [comment]
Yeah, I put the code away.

**Comment by dakujem** [comment]
Oh, sorry, I did not notice.

**Comment by dakujem** [comment]
Hello.
Is there any plan for a `4.2.x` patch release? This issue currently prevents me from migrating to 8. Thank you in advance!

**Comment by dg** [comment]
So use dev-4.2.x in the meantime.

**Comment by dakujem** [comment]
That works fine for development, not for production.

**Pull request merged**
