### PR TITLE
Make drivers more extensible

### PR DESCRIPTION
**Pull request by o5**
- bug fix? no
- new feature? yes
- BC break? no

I would like to override public static method `createException()` and add more exception types for PostgreSQL.

### CODE REVIEW

**Comment by o5** [comment]
Thank you!

**Comment by dg** [comment]
Thanks to you :)

**Comment by o5** [comment]
@dg I can prepare PR for master. Is there any chance that will be part of 4.0 release?

**Comment by dg** [comment]
I do not know where that commit disappeared. I fixed it..

**Comment by o5** [comment]
Thank you. Could you also create new tag? Something like `3.1.1`?

**Comment by dg** [comment]
Soon :)

**Pull request merged**
